#a, b = map(int(input()).split())
#a, b = int(input()).map(split())
a = int(input())
b = int(input())
print(a, b)
#a, b = map(split().int(input()))
#a, b = map(int(input()).int(input()))

a, b = map(int, input().split())
print(a, b)
#a, b = int(map( input().split()))
#a, b = map(int, input(),split())
#a, b = map(int. input().split())
#a, b = map(int.input(),split())